### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by cnaccio** [QuantConnect/quantconnect-stubs-generator#1]
Just wanted to recommend a little more documentation on how this solution works. It took me a bit to figure out, and I think it could be very helpful to explain how it works once it's installed. I didn't realized that it basically installed a QuantConnect package into your local python packages direction (env if you're using a virtual environment), which VS Code/Pylance will automatically use as a reference for autocomplete. Hope this helps!

P.S. Thanks so much for putting this together; this is way easier/cleaner than the various other solutions.

**Comment by jmerle** [comment]
Thank you! I have improved the documentation in c2693c4ea60d5c9c08b455f066dae0abf4adb7e1.
