### ISSUE TITLE
Add import statement to readme/pypi

### ISSUE THREAD

**Issue by shilewenuw** [QuantConnect/quantconnect-stubs-generator#2]
Add `from AlgorithmImports import *` to readme instructions and pypi

**Comment by jmerle** [comment]
Good idea, added in https://github.com/QuantConnect/quantconnect-stubs-generator/commit/5dbf3a3d3eee5e73cfa3ba2054278f231b074de1, the PyPI changes will be visible after the next release (which happens automatically when LEAN's master branch gets an update).
